# +------------------------------------------------------+
# |                                                      |
# |                                                      |
# |                                                      |
# |      _   _ _ _            _____           _          |
# |     | | | | | |_ _ __ __ |_   _|__   ___ | |___      |
# |     | | | | | __| '__/ _` || |/ _ \ / _ \| / __|     |
# |     | |_| | | |_| | | (_| || | (_) | (_) | \__ \     |
# |      \___/|_|\__|_|  \__,_||_|\___/ \___/|_|___/     |
# |                                                      |
# |                                                      |
# |                                                      |
# +------------------------------------------------------+

# Config file for UltraTools plugin.
